name: Build and Test
on:
  push:
    branches:
      - main
concurrency:
  group: ci-${{ github.event.repository.name }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Cache Maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup Java
        id: build
        uses: actions/setup-java@v1
        with:
          java-version: '13.0.2'
          architecture: x64

      - name: Build
        run: mvn clean verify -q

